---
# yamllint disable rule:line-length
name: Setup Action
description: |
  Sets up all the required env variables to be used by others

  ## Permissions

  Add the following permissions to the job

  ```yaml
  permissions:
    id-token: write
    contents: read
  ```

  ## Usage

  ```yaml
      - name: Setup
        uses: variant-inc/actions-setup@v2
  ```
outputs:
  image_version:
    description: >-
      Returns a semantic version that can used as a version for docker,
      helm, octopus, etc
    value: ${{ steps.set-version.outputs.image-version }}
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::108141096600:role/ops-github-runner
        aws-region: us-east-2
    - name: Get actions secret
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          SECRET_, arn:aws:secretsmanager:us-east-2:108141096600:secret:actions-secret-v2
        parse-json-secrets: true
    # Converts all SECRET__{env} type to {env} environment variable
    - shell: pwsh
      run: ${{ github.action_path }}/scripts/convertSecretsEnv.ps1

    - name: Get AWS Parameter store env
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/getAWSParameter.sh arn:aws:ssm:us-east-2:108141096600:parameter/actions-envs

    - name: Convert azure token into base64 encoded
      shell: bash
      run: |
        AZ_DEVOPS_BASE64_PAT=$(echo -n ${{ env.AZ_DEVOPS_PAT }} | base64)
        echo "::add-mask::$AZ_DEVOPS_BASE64_PAT"
        echo "AZ_DEVOPS_BASE64_PAT=$AZ_DEVOPS_BASE64_PAT" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ env.GITHUB_ENTERPRISE_KEY }}

    - name: Get the 10th last commit SHA
      id: get_commit
      shell: bash
      run: |
        commit_sha=$(git rev-list --max-count=9 HEAD | tail -1)
        echo "10th last commit SHA: $commit_sha"
        echo "sha=$commit_sha" >> "$GITHUB_OUTPUT"

    - name: GitGuardian scan
      if: ${{ env.DISABLE_GITGUARDIAN == 'false' }}
      uses: GitGuardian/ggshield-action@v1
      env:
        GITHUB_PUSH_BEFORE_SHA: ${{ steps.get_commit.outputs.sha }}
        GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
        GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        GITGUARDIAN_API_KEY: ${{ env.GITGUARDIAN_API_KEY }}

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: 5.x
    - name: Create GitVersion.yml if not exists
      shell: bash
      run: |
        FILE=GitVersion.yml
        if [ -f "$FILE" ]; then
          echo "::debug::$FILE exists."
        else
          echo "::debug::::debug::$FILE does not exist."
          echo "Creating $FILE..."
          cp ${{ github.action_path }}/GitVersion.yml GitVersion.yml
        fi
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3
      with:
        useConfigFile: true
    - name: Set Version
      id: set-version
      shell: bash
      run: ${{ github.action_path }}/scripts/set_version.sh

    - name: Set Sonar Keys
      shell: bash
      run: ${{ github.action_path }}/scripts/set_sonar_key.sh
    - name: Set Sonar Org
      shell: pwsh
      run: |
        $OWNER = [regex]::replace($env:GITHUB_REPOSITORY_OWNER, '-', '_').ToUpper()
        $SONAR_ORG = (get-item env:"SONAR_ORGS_${OWNER}").Value
        Add-Content -Path ${env:GITHUB_ENV} -Encoding utf8 -Value "SONAR_ORG=$SONAR_ORG"
