name: "Setup Action"
description: "Sets up all the required env variables to be used by others"
outputs:
  image_version:
    description: "Image Version"
    value: ${{ steps.setup.outputs.image-version }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
    - shell: pwsh
      id: setup
      run: |
        $versionNumber = "${env:GITVERSION_NUGETVERSION}.${env:GITHUB_RUN_NUMBER}"
        Write-Host "Setting environment variable IMAGE_VERSION to: $versionNumber"
        echo "image-version=${versionNumber}" >> $env:GITHUB_OUTPUT
        Add-Content -Path ${env:GITHUB_ENV} -Encoding utf8 -Value "IMAGE_VERSION=$versionNumber"
        Add-Content -Path ${env:GITHUB_ENV} -Encoding utf8 -Value "OCTOPUS_RELEASE_VERSION=$versionNumber"