---
# yamllint disable rule:line-length
name: Setup Action
description: |
  Checkout the repository and set up all the
  required environment variables to be used by other actions.

  ## Permissions

  Add the following permissions to the job

  ```yaml
  permissions:
    id-token: write
    contents: read
  ```

  ## Usage

  ```yaml
      - name: Setup
        uses: variant-inc/actions-setup/checkout@v2
  ```
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::108141096600:role/ops-github-runner
        aws-region: us-east-2
    - name: Get actions secret
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          SECRET_, arn:aws:secretsmanager:us-east-2:108141096600:secret:actions-secret-v2
        parse-json-secrets: true
    # Converts all SECRET__{env} type to {env} environment variable
    - shell: pwsh
      run: ${{ github.action_path }}/scripts/convertSecretsEnv.ps1

    - name: Get AWS Parameter store env
      shell: bash
      run: |
        git config --global url."https://usx-devops:${{ env.GITHUB_ENTERPRISE_KEY }}@github.com".insteadOf "https://github.com"
        ${{ github.action_path }}/scripts/getAWSParameter.sh arn:aws:ssm:us-east-2:108141096600:parameter/actions-envs

    - name: Convert azure token into base64 encoded
      shell: bash
      run: |
        AZ_DEVOPS_BASE64_PAT=$(echo -n ${{ env.AZ_DEVOPS_PAT }} | base64 -w 0)
        echo "::add-mask::$AZ_DEVOPS_BASE64_PAT"
        echo "AZ_DEVOPS_BASE64_PAT=$AZ_DEVOPS_BASE64_PAT" >> $GITHUB_ENV

    - name: Set Sonar Keys
      shell: bash
      run: ${{ github.action_path }}/scripts/set_sonar_key.sh
    - name: Set Sonar Org
      shell: pwsh
      run: |
        $OWNER = [regex]::replace($env:GITHUB_REPOSITORY_OWNER, '-', '_').ToUpper()
        $SONAR_ORG = (get-item env:"SONAR_ORGS_${OWNER}").Value
        Add-Content -Path ${env:GITHUB_ENV} -Encoding utf8 -Value "SONAR_ORG=$SONAR_ORG"

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ env.GITHUB_ENTERPRISE_KEY }}
