---
name: Linter

on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    name: Lint Code Base
    runs-on: eks

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_GITHUB_ACTIONS: false
