---
name: Linter

on:
  push:

jobs:
  lint:
    name: Lint Code Base
    runs-on: [ops]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Execute pre-commit
        # Run all pre-commit checks on max version supported
        run: pre-commit run --color=always --show-diff-on-failure --all-files