---
# yamllint disable rule:line-length
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main

jobs:
  Release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: 6.3.x
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v4

      - name: Create Release Action
        uses: variant-inc/actions-collection/create-release-tag@v2
